spring: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
tenants:
  datasources:
    vw:
      url: jdbc:h2:file:./vwdb
      driver: org.h2.Driver
      username: sa
      password: password
    bmw:
      url: jdbc:h2:file:./bmwdb
      driver: org.h2.Driver
      username: sa
      password: password
      
